version: '3.7'

services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-development
    command: sh -c './wait-for mysql-development:3306 -- npm start'

  mysql-development:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN
      MYSQL_DATABASE: event_reminder_db
    ports:
      - "3308:3306"