version: '3.7'

services:
  api_service:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-development:3306/event_reminder_db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql-development:
        condition: service_healthy
    command: sh -c './wait-for mysql-development:3306'

  mysql-development:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN
      MYSQL_DATABASE: event_reminder_db
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

